site_name: ML/MD course
site_url: https://pojeda.github.io/course-mlmd/
site_description: Material for the course ML/MD 
site_dir: site.build
theme:
  name: readthedocs
  locale: en
  logo: images/hpc2n-mlmm.png
    #  static_templates:
    #- sitemap.html
  include_sidebar: true
  font:
    code: Robot Mono
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view    
  tabs: true
  language: en
extra_css:
  - css/extra.css
    #extra_javascript:
    #  - js/popper.min.js
    #  - js/tippy-bundle.umd.js
    #  - js/clipboard.js

nav:
  - Home: index.md
  - Day 1: 
    - Mathematics for Machine Learning: day1.md
  - Day 2:
    - Machine Learning Concepts: day2.md
  - Day 3: 
    - ML for Molecular Systems: day3.md
  - Day 4:
    - Neural Networks: day4.md  
  - Day 5:
    - Graph Neural Networks: day5.md 
  - Day 6:
    - Generative Models: day6.md 
  - Day 7:
    - Advanced Models: day7.md 
  - Summary: summary.md
plugins:
  - search
  - external-markdown
  - mkdocstrings
  - markdown-exec
  - open-in-new-tab
  - mermaid2

markdown_extensions:
  - toc:
      toc_depth: 1-2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - smarty
  - tables
    #  - codehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.blocks.caption
  #- pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js